/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Presentacion;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class FormMateriales extends javax.swing.JFrame {
    
    private Inicio Inicio;
    private Metodos metodos = new Metodos();

    /**
     * Creates new form FormMateriales
     */
    public FormMateriales(Inicio ini) {
        initComponents();
        this.Inicio = ini;
        metodos.propiedadesFormMateriales(this);
        metodos.LlenarTabalaMaterial(this);
        metodos.ajustartablaFormMateriales(this);
        metodos.validarFiltroMaterial(this);
//        mnuEliminar.setVisible(false);
    }
    
    public Inicio getInicio() {
        return Inicio;
    }
    
    public void setInicio(Inicio Inicio) {
        this.Inicio = Inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DtbMaterial = new com.nqadmin.swingSet.SSDataGrid();
        tlbrMaterial = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        lblMaterial = new javax.swing.JLabel();
        chxbCodigoMater = new javax.swing.JCheckBox();
        jButton24 = new javax.swing.JButton();
        chxbNombreMater = new javax.swing.JCheckBox();
        cbxMaterial = new javax.swing.JComboBox<Object>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuCargar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuEliminar = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnuExportar = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Materiales");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DtbMaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DtbMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        DtbMaterial.setSSCellEditing(null);
        DtbMaterial.setSSDataGridHandler(null);
        DtbMaterial.setSSDataValue(null);
        DtbMaterial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jScrollPane2.setViewportView(DtbMaterial);

        tlbrMaterial.setRollover(true);
        tlbrMaterial.setPreferredSize(new java.awt.Dimension(28, 28));

        jButton1.setBackground(new java.awt.Color(225, 225, 225));
        jButton1.setText(" ");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton1);

        lblMaterial.setText("Material   ");
        tlbrMaterial.add(lblMaterial);

        chxbCodigoMater.setText("Codigo  ");
        chxbCodigoMater.setFocusable(false);
        chxbCodigoMater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chxbCodigoMater.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chxbCodigoMater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxbCodigoMaterActionPerformed(evt);
            }
        });
        tlbrMaterial.add(chxbCodigoMater);

        jButton24.setBackground(new java.awt.Color(225, 225, 225));
        jButton24.setText(" ");
        jButton24.setEnabled(false);
        jButton24.setFocusable(false);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton24);

        chxbNombreMater.setText("Nombre   ");
        chxbNombreMater.setFocusable(false);
        chxbNombreMater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chxbNombreMater.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chxbNombreMater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxbNombreMaterActionPerformed(evt);
            }
        });
        tlbrMaterial.add(chxbNombreMater);

        cbxMaterial.setVerifyInputWhenFocusTarget(false);
        tlbrMaterial.add(cbxMaterial);

        jButton2.setBackground(new java.awt.Color(225, 225, 225));
        jButton2.setText(" ");
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton2);

        jButton4.setBackground(new java.awt.Color(225, 225, 225));
        jButton4.setText(" ");
        jButton4.setEnabled(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton4);

        jButton5.setBackground(new java.awt.Color(225, 225, 225));
        jButton5.setText(" ");
        jButton5.setEnabled(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton5);

        jButton6.setBackground(new java.awt.Color(225, 225, 225));
        jButton6.setText(" ");
        jButton6.setEnabled(false);
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton6);

        jButton3.setBackground(new java.awt.Color(225, 225, 225));
        jButton3.setText(" ");
        jButton3.setEnabled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton3);

        btnBuscar.setText("Filtrar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        tlbrMaterial.add(btnBuscar);

        jButton7.setBackground(new java.awt.Color(225, 225, 225));
        jButton7.setText(" ");
        jButton7.setEnabled(false);
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton7);

        jButton8.setBackground(new java.awt.Color(225, 225, 225));
        jButton8.setText(" ");
        jButton8.setEnabled(false);
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton8);

        jButton9.setBackground(new java.awt.Color(225, 225, 225));
        jButton9.setText(" ");
        jButton9.setEnabled(false);
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton9);

        jButton10.setBackground(new java.awt.Color(225, 225, 225));
        jButton10.setText(" ");
        jButton10.setEnabled(false);
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton10);

        jButton11.setBackground(new java.awt.Color(225, 225, 225));
        jButton11.setText(" ");
        jButton11.setEnabled(false);
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton11);

        jButton12.setBackground(new java.awt.Color(225, 225, 225));
        jButton12.setText(" ");
        jButton12.setEnabled(false);
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton12);

        jButton13.setBackground(new java.awt.Color(225, 225, 225));
        jButton13.setText(" ");
        jButton13.setEnabled(false);
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton13);

        jButton14.setBackground(new java.awt.Color(225, 225, 225));
        jButton14.setText(" ");
        jButton14.setEnabled(false);
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton14);

        jButton15.setBackground(new java.awt.Color(225, 225, 225));
        jButton15.setText(" ");
        jButton15.setEnabled(false);
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton15);

        jButton16.setBackground(new java.awt.Color(225, 225, 225));
        jButton16.setText(" ");
        jButton16.setEnabled(false);
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton16);

        jButton17.setBackground(new java.awt.Color(225, 225, 225));
        jButton17.setText(" ");
        jButton17.setEnabled(false);
        jButton17.setFocusable(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton17);

        jButton18.setBackground(new java.awt.Color(225, 225, 225));
        jButton18.setText(" ");
        jButton18.setEnabled(false);
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton18);

        jButton19.setBackground(new java.awt.Color(225, 225, 225));
        jButton19.setText(" ");
        jButton19.setEnabled(false);
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton19);

        jButton20.setBackground(new java.awt.Color(225, 225, 225));
        jButton20.setText(" ");
        jButton20.setEnabled(false);
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton20);

        jButton21.setBackground(new java.awt.Color(225, 225, 225));
        jButton21.setText(" ");
        jButton21.setEnabled(false);
        jButton21.setFocusable(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton21);

        jButton22.setBackground(new java.awt.Color(225, 225, 225));
        jButton22.setText(" ");
        jButton22.setEnabled(false);
        jButton22.setFocusable(false);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton22);

        jButton23.setBackground(new java.awt.Color(225, 225, 225));
        jButton23.setText(" ");
        jButton23.setEnabled(false);
        jButton23.setFocusable(false);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbrMaterial.add(jButton23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbrMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tlbrMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu2.setText(" ");
        jMenu2.setEnabled(false);
        jMenuBar1.add(jMenu2);

        mnuCargar.setText("Cargar Datos");
        mnuCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCargarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCargar);

        jMenu3.setText(" ");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        mnuEliminar.setText("Eliminar Material");
        mnuEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuEliminarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuEliminar);

        jMenu4.setText(" ");
        jMenu4.setEnabled(false);
        jMenuBar1.add(jMenu4);

        mnuExportar.setText("Exportar");
        mnuExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExportarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuExportar);

        jMenu5.setText(" ");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCargarMouseClicked
        metodos.LlenarTabalaMaterial(this);
    }//GEN-LAST:event_mnuCargarMouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        metodos.ajustartablaFormMateriales(this);
    }//GEN-LAST:event_formComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        metodos.noabre = false;
    }//GEN-LAST:event_formWindowClosing

    private void mnuEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEliminarMouseClicked
        metodos.eliminarMaterialInventario(this);
    }//GEN-LAST:event_mnuEliminarMouseClicked

    private void mnuExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExportarMouseClicked
        metodos.ExportarExelMaterial(this);
    }//GEN-LAST:event_mnuExportarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        metodos.noabre = false;
    }//GEN-LAST:event_formWindowClosed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        metodos.BuscarEnMaterial(this);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chxbCodigoMaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxbCodigoMaterActionPerformed
        metodos.validarFiltroMaterial(this);
    }//GEN-LAST:event_chxbCodigoMaterActionPerformed

    private void chxbNombreMaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxbNombreMaterActionPerformed
        metodos.validarFiltroMaterial(this);
    }//GEN-LAST:event_chxbNombreMaterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.nqadmin.swingSet.SSDataGrid DtbMaterial;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JComboBox<Object> cbxMaterial;
    public javax.swing.JCheckBox chxbCodigoMater;
    public javax.swing.JCheckBox chxbNombreMater;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblMaterial;
    public javax.swing.JMenu mnuCargar;
    public javax.swing.JMenu mnuEliminar;
    public javax.swing.JMenu mnuExportar;
    public javax.swing.JToolBar tlbrMaterial;
    // End of variables declaration//GEN-END:variables
}
