/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Presentacion;

import GUI_TablaModel.ButoonEditor;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class FormEditarInventario extends javax.swing.JFrame {

    private Inicio Inicio;
    private Metodos metodos = new Metodos();
    public String Nombre;

    /**
     * Creates new form FormEditarInventario
     */
    public FormEditarInventario(Inicio ini) {
        initComponents();
        this.Inicio = ini;
        metodos.propiedadesFormEditarInventario(this);
    }

    public Inicio getInicio() {
        return Inicio;
    }

    public void setInicio(Inicio Inicio) {
        this.Inicio = Inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConten = new javax.swing.JPanel();
        lblCanExis = new javax.swing.JLabel();
        lblCamtEntre = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        txtNomMaterial = new javax.swing.JTextField();
        lblMater = new javax.swing.JLabel();
        txtCantiadExis = new javax.swing.JTextField();
        txtCantiDadEntre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblCanExis.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCanExis.setText("Cantidad En Existencia: ");

        lblCamtEntre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCamtEntre.setText("Cantidad Retirado: ");

        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.setPreferredSize(new java.awt.Dimension(79, 28));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        txtNomMaterial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNomMaterial.setBorder(null);
        txtNomMaterial.setPreferredSize(new java.awt.Dimension(300, 28));
        txtNomMaterial.setRequestFocusEnabled(false);

        lblMater.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblMater.setText("Nombre De Material: ");

        txtCantiadExis.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCantiadExis.setPreferredSize(new java.awt.Dimension(22, 28));
        txtCantiadExis.setRequestFocusEnabled(false);
        txtCantiadExis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantiadExisActionPerformed(evt);
            }
        });

        txtCantiDadEntre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCantiDadEntre.setPreferredSize(new java.awt.Dimension(22, 28));
        txtCantiDadEntre.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlContenLayout = new javax.swing.GroupLayout(pnlConten);
        pnlConten.setLayout(pnlContenLayout);
        pnlContenLayout.setHorizontalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMater)
                        .addGap(0, 0, 0)
                        .addComponent(txtNomMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(lblCanExis)
                        .addGap(0, 0, 0)
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addComponent(txtCantiadExis, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lblCamtEntre)
                                .addGap(0, 0, 0)
                                .addComponent(txtCantiDadEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenLayout.createSequentialGroup()
                                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)))))
                .addGap(10, 10, 10))
        );
        pnlContenLayout.setVerticalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMater)
                    .addComponent(txtNomMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCamtEntre)
                        .addComponent(txtCantiDadEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCanExis)
                        .addComponent(txtCantiadExis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantiadExisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantiadExisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantiadExisActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ButoonEditor.noabre = false;
    }//GEN-LAST:event_formWindowClosing

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        metodos.editarInventario(this);

    }//GEN-LAST:event_btnCambiarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ButoonEditor.noabre = false;
    }//GEN-LAST:event_formWindowClosed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormEditarInventario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiar;
    public javax.swing.JLabel lblCamtEntre;
    public javax.swing.JLabel lblCanExis;
    public javax.swing.JLabel lblMater;
    public javax.swing.JPanel pnlConten;
    public javax.swing.JTextField txtCantiDadEntre;
    public javax.swing.JTextField txtCantiadExis;
    public javax.swing.JTextField txtNomMaterial;
    // End of variables declaration//GEN-END:variables
}
