/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Presentacion;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class FormRegistrarMaterial extends javax.swing.JFrame {

    private Inicio Inicio;
    private Metodos metodos = new Metodos();
    public String Nombre;
    public int Id;

    /**
     * Creates new form FormEditarInventario
     * @param ini
     */
    public FormRegistrarMaterial(Inicio ini) {
        initComponents();
        this.Inicio = ini;
        metodos.propiedadesFormRejistarMterial(this);

    }

    public Inicio getInicio() {
        return Inicio;
    }

    public void setInicio(Inicio Inicio) {
        this.Inicio = Inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConten = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        lblCod1 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        txtNomMaterial = new javax.swing.JTextField();
        lblMater = new javax.swing.JLabel();
        txtCodMater = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        lblCod2 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblCod3 = new javax.swing.JLabel();
        txtElemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Material");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblCod.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod.setText("Codigo Siigo:  ");

        lblCod1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod1.setText("Linea: ");

        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCambiar.setText("Registrar");
        btnCambiar.setPreferredSize(new java.awt.Dimension(79, 28));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        txtNomMaterial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNomMaterial.setPreferredSize(new java.awt.Dimension(660, 28));
        txtNomMaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomMaterialFocusGained(evt);
            }
        });
        txtNomMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomMaterialKeyTyped(evt);
            }
        });

        lblMater.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblMater.setText("Nombre De Material: ");

        txtCodMater.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCodMater.setNextFocusableComponent(txtNomMaterial);
        txtCodMater.setPreferredSize(new java.awt.Dimension(150, 28));
        txtCodMater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodMaterKeyTyped(evt);
            }
        });

        txtLinea.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtLinea.setPreferredSize(new java.awt.Dimension(64, 28));

        lblCod2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod2.setText("Grupo: ");

        txtGrupo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtGrupo.setPreferredSize(new java.awt.Dimension(64, 28));
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        lblCod3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod3.setText("Elemento: ");

        txtElemento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtElemento.setPreferredSize(new java.awt.Dimension(64, 28));

        javax.swing.GroupLayout pnlContenLayout = new javax.swing.GroupLayout(pnlConten);
        pnlConten.setLayout(pnlContenLayout);
        pnlContenLayout.setHorizontalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(lblCod)
                        .addGap(0, 0, 0)
                        .addComponent(txtCodMater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(lblCod1)
                        .addGap(0, 0, 0)
                        .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblCod2)
                        .addGap(0, 0, 0)
                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblCod3)
                        .addGap(0, 0, 0)
                        .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(lblMater)
                        .addGap(0, 0, 0)
                        .addComponent(txtNomMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenLayout.setVerticalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCodMater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod1)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod2)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod3)
                    .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMater)
                    .addComponent(txtNomMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        metodos.noabre1 = false;
    }//GEN-LAST:event_formWindowClosing

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        metodos.rejistarMaterial(this);
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void txtCodMaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodMaterKeyTyped
        metodos.txtCodMaterKeyTyped(this, evt);
    }//GEN-LAST:event_txtCodMaterKeyTyped

    private void txtNomMaterialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomMaterialFocusGained
        metodos.txtNomMaterialFocusGained(this);
    }//GEN-LAST:event_txtNomMaterialFocusGained

    private void txtNomMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomMaterialKeyTyped
        metodos.TextoMayuscula(evt);
    }//GEN-LAST:event_txtNomMaterialKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       metodos.noabre1 = false;
    }//GEN-LAST:event_formWindowClosed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormEditarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormEditarInventario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiar;
    public javax.swing.JLabel lblCod;
    public javax.swing.JLabel lblCod1;
    public javax.swing.JLabel lblCod2;
    public javax.swing.JLabel lblCod3;
    public javax.swing.JLabel lblMater;
    public javax.swing.JPanel pnlConten;
    public javax.swing.JTextField txtCodMater;
    public javax.swing.JTextField txtElemento;
    public javax.swing.JTextField txtGrupo;
    public javax.swing.JTextField txtLinea;
    public javax.swing.JTextField txtNomMaterial;
    // End of variables declaration//GEN-END:variables

}
