/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Presentacion;

import GUI_TablaModel.ButoonEditor1;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class FormEditarMaterial extends javax.swing.JFrame {

    private FormMateriales Mateial;
    private Metodos metodos = new Metodos();
    public String Nombre;
    public int Id;

    /**
     * Creates new form FormEditarInventario
     */
    public FormEditarMaterial(FormMateriales mater) {
        initComponents();
        this.Mateial = mater;
        metodos.propiedadesFormEditarMterial(this);
    }

    public FormMateriales getMateial() {
        return Mateial;
    }

    public void setMateial(FormMateriales Mateial) {
        this.Mateial = Mateial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConten = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        lblCod1 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        txtNomMaterial = new javax.swing.JTextField();
        lblMater = new javax.swing.JLabel();
        txtCodMater = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        lblCod2 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblCod3 = new javax.swing.JLabel();
        txtElemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblCod.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod.setText("Codigo Siigo:  ");

        lblCod1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod1.setText("Linea: ");

        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.setPreferredSize(new java.awt.Dimension(79, 28));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        txtNomMaterial.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNomMaterial.setPreferredSize(new java.awt.Dimension(660, 28));
        txtNomMaterial.setRequestFocusEnabled(false);
        txtNomMaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomMaterialFocusGained(evt);
            }
        });
        txtNomMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomMaterialKeyTyped(evt);
            }
        });

        lblMater.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblMater.setText("Nombre De Material: ");

        txtCodMater.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCodMater.setNextFocusableComponent(txtNomMaterial);
        txtCodMater.setPreferredSize(new java.awt.Dimension(150, 28));
        txtCodMater.setRequestFocusEnabled(false);
        txtCodMater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodMaterKeyTyped(evt);
            }
        });

        txtLinea.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtLinea.setPreferredSize(new java.awt.Dimension(64, 28));
        txtLinea.setRequestFocusEnabled(false);

        lblCod2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod2.setText("Grupo: ");

        txtGrupo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtGrupo.setPreferredSize(new java.awt.Dimension(64, 28));
        txtGrupo.setRequestFocusEnabled(false);

        lblCod3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCod3.setText("Elemento: ");

        txtElemento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtElemento.setPreferredSize(new java.awt.Dimension(64, 28));
        txtElemento.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlContenLayout = new javax.swing.GroupLayout(pnlConten);
        pnlConten.setLayout(pnlContenLayout);
        pnlContenLayout.setHorizontalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addComponent(lblCod)
                                .addGap(0, 0, 0)
                                .addComponent(txtCodMater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addComponent(lblCod1)
                                .addGap(0, 0, 0)
                                .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblCod2)
                                .addGap(0, 0, 0)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblCod3)
                                .addGap(0, 0, 0)
                                .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addComponent(lblMater)
                                .addGap(0, 0, 0)
                                .addComponent(txtNomMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        pnlContenLayout.setVerticalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCodMater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod1)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod2)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod3)
                    .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMater)
                    .addComponent(txtNomMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ButoonEditor1.noabre = false;
    }//GEN-LAST:event_formWindowClosing

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        metodos.editarMaterial(this);
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void txtCodMaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodMaterKeyTyped
        metodos.txtCodMaterKeyTyped(this, evt);
    }//GEN-LAST:event_txtCodMaterKeyTyped

    private void txtNomMaterialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomMaterialFocusGained
        metodos.txtNomMaterialFocusGained(this);
    }//GEN-LAST:event_txtNomMaterialFocusGained

    private void txtNomMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomMaterialKeyTyped
        metodos.TextoMayuscula(evt);
    }//GEN-LAST:event_txtNomMaterialKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ButoonEditor1.noabre = false;
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiar;
    public javax.swing.JLabel lblCod;
    public javax.swing.JLabel lblCod1;
    public javax.swing.JLabel lblCod2;
    public javax.swing.JLabel lblCod3;
    public javax.swing.JLabel lblMater;
    public javax.swing.JPanel pnlConten;
    public javax.swing.JTextField txtCodMater;
    public javax.swing.JTextField txtElemento;
    public javax.swing.JTextField txtGrupo;
    public javax.swing.JTextField txtLinea;
    public javax.swing.JTextField txtNomMaterial;
    // End of variables declaration//GEN-END:variables
}
